language: node_js

node_js:
  - '0.10'
  - '0.12'
  - 'iojs'

env:
  - CXX=g++-4.8
  - CXX=g++-4.6

before_install: |
  if [ "$CXX" = "g++-4.8" ]; then
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    sudo apt-get update -qq
    sudo apt-get install -qq g++-4.8
  fi
