language: node_js

node_js:
- '0.10'
- '0.11'
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8 gcc-4.8-multilib g++-4.8-multilib
  - export CXX=g++-4.8
script:
- npm run build
- npm test
matrix:
  allow_failures:
    - node_js: '0.11'
