language: node_js

node_js:
- '0.10'
- '0.12'
- 'iojs'

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX=g++-4.8
